console.log("Câu 1 :");
console.log(" a)1.Khi tên biến bắt đầu bằng một số. \n   2.Khi tên biến chứa những ký tự đặc biệt. \n   3.Khi tên biến trùng với các keyword  có trong js." );
console.log(" b)Cách để ktra kiểu dữ liệu của dữ liệu dùng toán tử typeof");
console.log("Câu 2 : \n - Front-end consists of HTML,CSS,JS \n - HTML content \n - CSS Decoration, appearance  \n - JS direct user interaction.");
console.log("Câu 3 : ");
let message = "Coding is great";
console.log(message);
let studentCount = 0;
console.log(studentCount);
console.log("Câu 4 : ");
message="Coding might not be easy, but still great";
console.log(message);
studentCount=16;
console.log(studentCount);
let a = message.toLowerCase();
console.log(a);
console.log(studentCount+1);
alert(" Câu 5: Have a good day !");
let name = prompt(" Câu 6: What is your name?");
alert(`Hi ${name}`);
let name1 = prompt(" Câu 7: Enter your first name: ");
let name2 = prompt("Enter your last name: ");
alert(`Hi ${name1} ${name2}`);
let hinhVuong = prompt("Câu 8: Nhập cạnh hình vuông : ");
alert(`Diện tích hình vuông là : ${(hinhVuong)*(hinhVuong)}`);
let hinhTron = prompt("Câu 9: Nhập bán kính hình tròn : ");
alert(`Diện tích hình tròn là : ${(hinhTron)*(hinhTron)*(3.14)}`);
let nhietdo = prompt("Câu 10: Nhập nhiệt độ ở độ C : ");
alert(`${nhietdo} (C) = ${(nhietdo)*(1.8)+(32)} (F)`);